name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run tests
        run: npm test
      - name: Run Build
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')
    steps:
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  notify_failure:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Build Failed
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@1264842173619109949>"
          title: "Failure in CI/CD pipeline"
          description: "Build Failed for commit"
          url: "https://github.com/djtimog/fs-ci-cd"
          username: Christian Ogunleye

  notify_success:
    needs: [deploy]
    runs-on: ubuntu
    if: success()
    steps:
      - name: Deployment Successful
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@1264842173619109949>"
          title: "Deployment Details"
          description: "The deployment was successful"
          username: Christian Ogunleye

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      
