name: Deployment pipeline

on: 
  push:
    branches:
      - main
  
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs: 
  deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: 
          node-version: '24'
      - name: install the dependancies
        run: npm install

      - name: Check style
        run: npm run eslint
      
      - name: Run Test
        run: npm test
        
      - name: Build step
        run: npm run build

      - name: Install playwright drivers 
        run:  | 
          npx playwright install 
          sudo npx playwright install-deps        

      - name: end-to-end test
        run:
          npm run test:e2e
      
      - name: end-to-end test
        run: npx playwright test
      
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }} 
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  
  tag_release: 
    needs: deployment_pipeline

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '24'
      - name: install the dependancies
        run: npm install

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 